# Generated by Django 5.0.1 on 2024-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('property_type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('land', 'land')], default='house', max_length=200)),
                ('bedroom_count', models.PositiveIntegerField(null=True)),
                ('square_footage', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
